# ========================
# Clash-Fallback ä¼˜åŒ–é…ç½®
# ========================

# æœºåœºèŠ‚ç‚¹è®¢é˜…

proxy-providers:

  æµé‡å…‰:
    url: "https://"  
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿     

proxies:
  - {name: ç›´è¿, type: direct}
  - {name: æ‹’ç», type: reject}

# ========================
# ä¸»è¦ç«¯å£è®¾ç½®
# ========================
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895

allow-lan: true
mode: rule
log-level: info

external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-name: zashboard
external-ui-url: https://gh-proxy.com/github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip
secret: "123456"

# ========================
# DNS è®¾ç½®
# ========================
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.20.0.1/16
  nameserver:
    - 223.5.5.5
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - +.lan
    - +.local
    - geosite:cn
    - +.saojc.xyz   
    
ipv6: false

# ========================
# TUN æ¨¡å—
# ========================
tun:
  enable: true
  stack: gvisor
  device: utun
  endpoint-independent-nat: true
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false

profile:
  store-selected: true
  store-fake-ip: true
 

# ========================
# ç­–ç•¥ç»„å®šä¹‰
# ========================
proxy-groups:
  # ä¸šåŠ¡åˆ†æµç»„
  - name: AI
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»
  - name: TIKTOK
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»
  - name: NETFLIX
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»
  - name: Apple
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»
  - name: Microsoft
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»
  - name: Games
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»
  - name: YOUTUBE
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»
  - name: GOOGLE
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»
  - name: å›½å¤–
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»
  - name: å›½å†…
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»
  - name: å…¶ä»–
    type: select
    proxies:
      - ç›´è¿
      - æ‰€æœ‰-è‡ªåŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
      - å°æ¹¾-è‡ªåŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
      - ç¾å›½-è‡ªåŠ¨
      - æ‹’ç»

  - name: æ‰€æœ‰-è‡ªåŠ¨
    type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 100
    interval: 300
    filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"

  - name: é¦™æ¸¯-è‡ªåŠ¨
    type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 100
    interval: 300
    filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"
 
  - name: å°æ¹¾-è‡ªåŠ¨
    type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 100
    interval: 300
    filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan)).*$"

  - name: æ—¥æœ¬-è‡ªåŠ¨
    type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 100
    interval: 300
    filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"

  - name: æ–°åŠ å¡-è‡ªåŠ¨
    type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 100
    interval: 300
    filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"

  - name: ç¾å›½-è‡ªåŠ¨
    type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 100
    interval: 300
    filter: "(?=.*(å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"
  

# ========================
# è§„åˆ™å¼•æ“ï¼ˆrulesï¼‰
# ========================
rules:
  - RULE-SET,ChatGPT / Domain,AI
  - RULE-SET,Claude / Domain,AI
  - RULE-SET,Gemini / Domain,AI
  - RULE-SET,Groq / Domain,AI
  - RULE-SET,Microsoft / Domain,Microsoft
  - RULE-SET,Apple / Domain,Apple
  - RULE-SET,Apple-CN / Domain,Apple  
  - RULE-SET,TikTok / Domain,TIKTOK
  - RULE-SET,Netflix / Domain,NETFLIX
  - RULE-SET,Netflix / IP,NETFLIX,no-resolve
  - RULE-SET,Steam / Domain,Games
  - RULE-SET,Epic / Domain,Games
  - RULE-SET,EA / Domain,Games
  - RULE-SET,Blizzard / Domain,Games
  - RULE-SET,UBI / Domain,Games
  - RULE-SET,PlayStation / Domain,Games
  - RULE-SET,Nintend / Domain,Games
  - RULE-SET,Youtube / Domain,YOUTUBE
  - RULE-SET,Google / Domain,GOOGLE
  - RULE-SET,Google / IP,GOOGLE
  - RULE-SET,Globe / Domain,å›½å¤–  
  - RULE-SET,China / Domain,å›½å†…
  - RULE-SET,China / IP,å›½å†…,no-resolve
  - MATCH,å…¶ä»–

# ========================
# è§„åˆ™é›†æä¾›è€…
# ========================

rule-providers:

  # 1. ChatGPT / Domain (<<: *domain)
  ChatGPT / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.mrs"

  # 2. Gemini / Domain (<<: *class)
  Gemini / Domain:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: "https://raw.githubusercontent.com/eeerichou/clash/refs/heads/main/Gemini.list"

  # 3. Groq / Domain (<<: *domain)
  Groq / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/groq.mrs"

  # 4. Claude / Domain (<<: *class)
  Claude / Domain:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list"

  # 5. Apple-CN / Domain (<<: *domain)
  Apple-CN / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-cn.mrs"

  # 6. Apple / Domain (<<: *domain)
  Apple / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.mrs"

  # 7. Microsoft / Domain (<<: *domain)
  Microsoft / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs"

  # 8. TikTok / Domain (<<: *domain)
  TikTok / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs"

  # 9. Netflix / Domain (<<: *domain)
  Netflix / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.mrs"

  # 10. Netflix / IP (<<: *ip)
  Netflix / IP:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/netflix.mrs"

  # 11. Steam / Domain (<<: *domain)
  Steam / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam.mrs"

  # 12. Epic / Domain (<<: *class)
  Epic / Domain:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list"

  # 13. EA / Domain (<<: *class)
  EA / Domain:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list"

  # 14. Blizzard / Domain (<<: *class)
  Blizzard / Domain:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list"

  # 15. UBI / Domain (<<: *class)
  UBI / Domain:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list"

  # 16. PlayStation / Domain (<<: *class)
  PlayStation / Domain:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PlayStation/PlayStation.list"

  # 17. Nintend / Domain (<<: *class)
  Nintend / Domain:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list"

  # 18. Youtube / Domain (<<: *domain)
  Youtube / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/youtube.mrs"

  # 19. Google / Domain (<<: *domain)
  Google / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs"

  # 20. Google / IP (<<: *ip)
  Google / IP:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs"

  # 21. Globe / Domain (<<: *class)
  Globe / Domain:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list"

  # 22. China / Domain (<<: *domain)
  China / Domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.mrs"

  # 23. China / IP (<<: *ip)
  China / IP:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs"


